server:
  error:
    include-message: never
    include-stacktrace: never

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smart_wash?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&useSSL=true
    username: root
    password: admin123

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 3

mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  setting:
    language: zh_cn
