export class OrderVo {
  orderId: number | null = null
  userId: number | null = null
  schoolId: number | null = null
  lockerId: number | null = null
  orderNo: string | null = null
  laundryItemsId: number | null = null
  totalPrice: number | null = null
  payPrice: number | null = null
  status: string | null = null
  pickupCode: string | null = null
  createdAt: string | null = null
  updatedAt: string | null = null
}