name: web-ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SmartWashWeb
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: SmartWashWeb/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
